apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: gshub-api

build:
  artifacts:
  - image: gshub-api
    context: .
    docker:
      dockerfile: Dockerfile.dev
    sync:
      manual:
      - src: "**/*.go"
        dest: /app
  tagPolicy:
    customTemplate:
      template: "latest"
  local:
    push: false
    useBuildkit: true

deploy:
  kustomize:
    paths:
    - ../k8s/overlays/dev

portForward:
- resourceType: service
  resourceName: api
  namespace: gshub
  port: 8080
  localPort: 8080