apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: gshub-api

build:
  artifacts:
  - image: gshub-api
    context: .
    docker:
      dockerfile: Dockerfile.dev
    sync:
      manual:
      - src: "**/*.go"
        dest: /app
  # Supervisor images for game servers
  # - image: dasior/supervisor
  #   context: ../supervisor
  #   docker:
  #     dockerfile: Dockerfile
  # - image: dasior/supervisor-minecraft
  #   context: ../supervisor
  #   docker:
  #     dockerfile: Dockerfile.minecraft
  # - image: dasior/supervisor-valheim
  #   context: ../supervisor
  #   docker:
  #     dockerfile: Dockerfile.valheim
  # - image: dasior/supervisor-enshrouded
  #   context: ../supervisor
  #   docker:
  #     dockerfile: Dockerfile.enshrouded
  # tagPolicy:
  #   customTemplate:
  #     template: "latest"
  local:
    push: false
    useBuildkit: true

deploy:
  kustomize:
    paths:
    - ../k8s/overlays/dev

portForward:
- resourceType: service
  resourceName: api
  namespace: gshub
  port: 8080
  localPort: 8080
- resourceType: service
  resourceName: postgresql
  namespace: gshub
  port: 5432
  localPort: 5432
# Internal API port for supervisor communication
- resourceType: service
  resourceName: api
  namespace: gshub
  port: 8081
  localPort: 8081